"use client";

import { useState, useEffect } from "react";

import { useTranslations } from "next-intl";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useUserStore } from "@/stores/user/user-provider";

import {
  buildAppointmentPayload,
  calculateDuration,
  fetchAndProcessPICs,
  initializeFormFromSlot,
  validateFormSubmission,
  fetchClientProjects,
} from "../_hooks/create-appointment-dialog-hooks";

import type {
  Appointment,
  PMAvailabilitySlot,
  MeetingType,
  PIC,
  ProjectContext,
} from "./calendar-config";
import { CreateAppointmentDialogForm } from "./create-appointment-dialog-form";

interface CreateAppointmentDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (appointment: Omit<Appointment, "id" | "createdAt" | "updatedAt">) => void;
  initialSlot?: PMAvailabilitySlot;
  projectContext?: ProjectContext;
}

export function CreateAppointmentDialog({
  open,
  onOpenChange,
  onSave,
  initialSlot,
  projectContext,
}: CreateAppointmentDialogProps) {
  const t = useTranslations("Appointments");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [picId, setPicId] = useState("");
  const [date, setDate] = useState("");
  const [startTime, setStartTime] = useState("");
  const [endTime, setEndTime] = useState("");
  const [type, setType] = useState<MeetingType>("online");
  const [location, setLocation] = useState("");
  const [meetingLink, setMeetingLink] = useState("");
  const [useAutoGeneratedLink, setUseAutoGeneratedLink] = useState(true);
  const [pics, setPics] = useState<PIC[]>([]);
  const [loadingPics, setLoadingPics] = useState(false);
  const [projectId, setProjectId] = useState("");
  const [projects, setProjects] = useState<{ id: string; name: string }[]>([]);
  const [loadingProjects, setLoadingProjects] = useState(false);

  const currentUser = useUserStore(state => state.currentUser);
  const isClient = useUserStore(state => state.isClient());
  const userRole = useUserStore(state => state.currentUser?.role);

  // Fetch PICs
  useEffect(() => {
    fetchAndProcessPICs(projectContext, setPics, setPicId, setLoadingPics);
  }, [projectContext]);

  // Fetch client projects if user is client
  useEffect(() => {
    if (open && isClient && currentUser && userRole) {
      fetchClientProjects(currentUser.id, userRole, setProjects, setLoadingProjects);
    }
  }, [open, isClient, currentUser, userRole]);

  // Initialize form from initialSlot
  useEffect(() => {
    initializeFormFromSlot(initialSlot, open, {
      setPicId,
      setDate,
      setStartTime,
      setEndTime,
      setType,
      setTitle,
      setDescription,
      setLocation,
    });
  }, [initialSlot, open]);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();

    const { valid, selectedPM } = validateFormSubmission(
      title,
      picId,
      projectId,
      date,
      startTime,
      endTime,
      pics,
      isClient
    );
    if (!valid || !selectedPM) return;

    const duration = calculateDuration(startTime, endTime);
    const payload = buildAppointmentPayload(
      title,
      description,
      picId,
      projectId,
      selectedPM,
      date,
      startTime,
      endTime,
      duration,
      type,
      type === "online" && !useAutoGeneratedLink ? meetingLink : location
    );

    onSave(payload);
    onOpenChange(false);
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{t("createAppointmentDialogTitle")}</DialogTitle>
          <DialogDescription>
            {projectContext?.projectName
              ? t("createAppointmentDialogDescriptionWithProject", {
                  projectName: projectContext.projectName,
                })
              : t("createAppointmentDialogDescription")}
          </DialogDescription>
        </DialogHeader>
        <CreateAppointmentDialogForm
          title={title}
          setTitle={setTitle}
          description={description}
          setDescription={setDescription}
          picId={picId}
          setPicId={setPicId}
          pics={pics}
          loadingPics={loadingPics}
          projectContext={projectContext}
          date={date}
          setDate={setDate}
          type={type}
          setType={setType}
          startTime={startTime}
          setStartTime={setStartTime}
          endTime={endTime}
          setEndTime={setEndTime}
          location={location}
          setLocation={setLocation}
          meetingLink={meetingLink}
          setMeetingLink={setMeetingLink}
          useAutoGeneratedLink={useAutoGeneratedLink}
          setUseAutoGeneratedLink={setUseAutoGeneratedLink}
          projectId={projectId}
          setProjectId={setProjectId}
          projects={projects}
          loadingProjects={loadingProjects}
          isClient={isClient}
          onSubmit={handleSubmit}
          onCancel={() => onOpenChange(false)}
        />
      </DialogContent>
    </Dialog>
  );
}
