/**
 * Form component for CreateAppointmentDialog
 */

import { Button } from "@/components/ui/button";

import type { MeetingType, PIC, ProjectContext } from "./calendar-config";
import {
  MeetingLocationFields,
  PICField,
  TimeFields,
  TitleDescriptionFields,
  DateTypeFields,
} from "./create-appointment-dialog-form-fields";

interface Project {
  id: string;
  name: string;
}

interface CreateAppointmentDialogFormProps {
  title: string;
  setTitle: (title: string) => void;
  description: string;
  setDescription: (desc: string) => void;
  picId: string;
  setPicId: (id: string) => void;
  pics: PIC[];
  loadingPics: boolean;
  projectId: string;
  setProjectId: (id: string) => void;
  projects: Project[];
  loadingProjects: boolean;
  projectContext?: ProjectContext;
  date: string;
  setDate: (date: string) => void;
  type: MeetingType;
  setType: (type: MeetingType) => void;
  startTime: string;
  setStartTime: (time: string) => void;
  endTime: string;
  setEndTime: (time: string) => void;
  location: string;
  setLocation: (location: string) => void;
  meetingLink: string;
  setMeetingLink: (link: string) => void;
  useAutoGeneratedLink: boolean;
  setUseAutoGeneratedLink: (value: boolean) => void;
  onSubmit: (e: React.FormEvent) => void;
  onCancel: () => void;
  isClient?: boolean;
}

export function CreateAppointmentDialogForm({
  title,
  setTitle,
  description,
  setDescription,
  picId,
  setPicId,
  pics,
  loadingPics,
  projectId,
  setProjectId,
  projects,
  loadingProjects,
  projectContext,
  date,
  setDate,
  type,
  setType,
  startTime,
  setStartTime,
  endTime,
  setEndTime,
  location,
  setLocation,
  meetingLink,
  setMeetingLink,
  useAutoGeneratedLink,
  setUseAutoGeneratedLink,
  onSubmit,
  onCancel,
  isClient = false,
}: CreateAppointmentDialogFormProps) {
  return (
    <form onSubmit={onSubmit} className="space-y-4">
      <TitleDescriptionFields
        title={title}
        setTitle={setTitle}
        description={description}
        setDescription={setDescription}
      />

      <PICField
        pmId={picId}
        setPmId={setPicId}
        pics={pics}
        loadingPics={loadingPics}
        projectContext={projectContext}
      />

      {isClient && (
        <div className="grid gap-2">
          <label htmlFor="project" className="text-sm font-medium">
            Project <span className="text-destructive">*</span>
          </label>
          <select
            id="project"
            value={projectId}
            onChange={e => setProjectId(e.target.value)}
            className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50"
            disabled={loadingProjects}
            required
          >
            <option value="">{loadingProjects ? "Loading projects..." : "Select a project"}</option>
            {(projects || []).map(project => (
              <option key={project.id} value={project.id}>
                {project.name}
              </option>
            ))}
          </select>
        </div>
      )}

      <DateTypeFields date={date} setDate={setDate} type={type} setType={setType} />

      <TimeFields
        startTime={startTime}
        setStartTime={setStartTime}
        endTime={endTime}
        setEndTime={setEndTime}
      />

      <MeetingLocationFields
        type={type}
        location={location}
        setLocation={setLocation}
        meetingLink={meetingLink}
        setMeetingLink={setMeetingLink}
        useAutoGeneratedLink={useAutoGeneratedLink}
        setUseAutoGeneratedLink={setUseAutoGeneratedLink}
      />

      <div className="flex justify-end gap-2">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button
          type="submit"
          disabled={
            !title ||
            !picId ||
            !date ||
            !startTime ||
            !endTime ||
            (isClient && !projectId) ||
            (type === "online" && !useAutoGeneratedLink && !meetingLink)
          }
        >
          Create Appointment
        </Button>
      </div>
    </form>
  );
}
