/**
 * Form component for CreateAppointmentDialog
 */

import { Button } from "@/components/ui/button";

import type { MeetingType, PIC, ProjectContext } from "./calendar-config";
import {
  MeetingLocationFields,
  PICField,
  TimeFields,
  TitleDescriptionFields,
  DateTypeFields,
} from "./create-appointment-dialog-form-fields";

interface CreateAppointmentDialogFormProps {
  title: string;
  setTitle: (title: string) => void;
  description: string;
  setDescription: (desc: string) => void;
  picId: string;
  setPicId: (id: string) => void;
  pics: PIC[];
  loadingPics: boolean;
  projectContext?: ProjectContext;
  date: string;
  setDate: (date: string) => void;
  type: MeetingType;
  setType: (type: MeetingType) => void;
  startTime: string;
  setStartTime: (time: string) => void;
  endTime: string;
  setEndTime: (time: string) => void;
  location: string;
  setLocation: (location: string) => void;
  meetingLink: string;
  setMeetingLink: (link: string) => void;
  useAutoGeneratedLink: boolean;
  setUseAutoGeneratedLink: (value: boolean) => void;
  onSubmit: (e: React.FormEvent) => void;
  onCancel: () => void;
}

export function CreateAppointmentDialogForm({
  title,
  setTitle,
  description,
  setDescription,
  picId,
  setPicId,
  pics,
  loadingPics,
  projectContext,
  date,
  setDate,
  type,
  setType,
  startTime,
  setStartTime,
  endTime,
  setEndTime,
  location,
  setLocation,
  meetingLink,
  setMeetingLink,
  useAutoGeneratedLink,
  setUseAutoGeneratedLink,
  onSubmit,
  onCancel,
}: CreateAppointmentDialogFormProps) {
  return (
    <form onSubmit={onSubmit} className="space-y-4">
      <TitleDescriptionFields
        title={title}
        setTitle={setTitle}
        description={description}
        setDescription={setDescription}
      />

      <PICField
        pmId={picId}
        setPmId={setPicId}
        pics={pics}
        loadingPics={loadingPics}
        projectContext={projectContext}
      />

      <DateTypeFields date={date} setDate={setDate} type={type} setType={setType} />

      <TimeFields
        startTime={startTime}
        setStartTime={setStartTime}
        endTime={endTime}
        setEndTime={setEndTime}
      />

      <MeetingLocationFields
        type={type}
        location={location}
        setLocation={setLocation}
        meetingLink={meetingLink}
        setMeetingLink={setMeetingLink}
        useAutoGeneratedLink={useAutoGeneratedLink}
        setUseAutoGeneratedLink={setUseAutoGeneratedLink}
      />

      <div className="flex justify-end gap-2">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button
          type="submit"
          disabled={
            !title ||
            !picId ||
            !date ||
            !startTime ||
            !endTime ||
            (type === "online" && !useAutoGeneratedLink && !meetingLink)
          }
        >
          Create Appointment
        </Button>
      </div>
    </form>
  );
}
